Napa/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Napa.Models
{
    public class User
    {
        

        [Key]
        public int Id { get; set; }
        public string Username { get; set; }

        public string Password { get; set; }
    }
}

Napa/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Napa.Models;
using Napa.Services;
using Napa.ViewModels;

namespace Napa.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _service;
        private readonly IUserService _user;

        public ProductController(IProductService service, IUserService user)
        {
            _service = service;
            _user = user;
        }
        public async Task<IActionResult> Index()
        {
            var product = await _service.GetAll();
            return View(product);
        }
        public IActionResult Create()
        {
            return View(new ProductVM());
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title,Quantiy,Price")]Product products)
        {
            if (!ModelState.IsValid)
            {
                return View(products);
            }
            await _service.InsertAsync(products);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await _service.GetAsync(id);
            if(product == null) return View("Error");
            return View(product);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var product = await _service.GetAsync(id);
            if(product == null) return View("NotFound");
            return View(product);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Quantiy,Price")]Product products)
        {
            if (!ModelState.IsValid)
            {
                return View(products);
            }
            await _service.UpdateAsync(products);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var product = await _service.GetAsync(id);
            if(product == null) return View("NotFound");
            return View(product);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, [Bind("Id,Title,Quantiy,Price")]Product products)
        {
            var product = await _service.GetAsync(id);
            if(product == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

Napa/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Napa.Models;
using Napa.Services;

namespace Napa.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _service;

        public UserController(IUserService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Users()
        {
            var user = await _service.GetAll();
            return View(user);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var user = await _service.GetAsync(id);
            if(user == null) return View("NotFound");
            return View(user);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteUserConfirmed(int id, [Bind("Username,Password")]User users)
        {
            var user = _service.GetAsync(id);
            if(user == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Users));
        }

        public async Task<IActionResult> Details(int id)
        {
            var user = await _service.GetAsync(id);
            if(user == null) return View("Error");
            return View(user);
        }

    }
}

Napa/Views/User/Delete.cshtml
@model User;

@{
    ViewData["Title"] = "Details of User";
}
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">Napa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Users">Users</a>
                        </li>
                    </ul>
                </div>
                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Registration</a>
                        </li>
                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
            </div>
        </nav>
    </header>
<div class="row">
    <div class="col-md-6 offset-3">
        <p>
            <h4>Details for @Model.Username </h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">

                    <div class="form-group">
                        <label asp-for="Username" class="control-label"></label>
                        <input asp-for="Username" class="form-control" readonly/>
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" readonly/>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Confirm" class="btn btn-danger float right" />
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Users">Cancel</a>
                    </div>
            </div>
        </div>
    </div>
</div>

Napa/Views/User/Details.cshtml
@model User;

@{
    ViewData["Title"] = "Details of User";
}
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">Napa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Users">Users</a>
                        </li>
                    </ul>
                </div>
                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Registration</a>
                        </li>
                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
            </div>
        </nav>
    </header>
<div class="row">
    <div class="col-md-6 offset-3">
        <p>
            <h4>Details for @Model.Username </h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">

                    <div class="form-group">
                        <label asp-for="Username" class="control-label"></label>
                        <input asp-for="Username" class="form-control" readonly/>
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" readonly/>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <a class="btn btn-outline-secondary" asp-action="Users">Cancel</a>
                        <a asp-controller="User" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"><i class="bi bi-trash"></i>Delete</a>
                    </div>
                    
            </div>
        </div>
    </div>
</div>

Napa/Views/User/Users.cshtml
@model IEnumerable<User>

@{
    ViewData["Title"] = "List of Users";
}
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">Napa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Users">Users</a>
                        </li>
                    </ul>
                </div>
                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Registration</a>
                        </li>
                <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
            </div>
        </nav>
    </header>
<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table text-center">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Username)</th>
                    <th>@Html.DisplayNameFor(model => model.Password)</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Username)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Password)
                        </td>
                        <td class="align-middle">
                            <a asp-controller="User" asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Details</a>
                            <a asp-controller="User" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="bi bi-trash"></i>Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div style="position: fixed; right: 25px; bottom: 25px" class="text-white">
    <a asp-controller="Actors" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Add New </a>
</div>